### ISSUE TITLE
Undefined error at Line 203

### ISSUE THREAD

**Issue by erkr** [TheFes/relative-time-plus#20]
Hi 
Thanks for this great enhanced version of relative time.
Most of the time it works great, but a few times a day I see this error in my log. It triggers at line 203 in relative_time_plus:
```text 
Logger: homeassistant.helpers.event
Source: helpers/template.py:570 
First occurred: 09:12:31 (1 occurrences) 
Last logged: 09:12:31

Error while processing template: Template<template=({% from 'relative_time_plus.jinja' import relative_time_plus %} {{ 'wait' if not has_value(config.entity) else relative_time_plus(states[config.entity].last_changed, parts=2, week=false, time=true, abbr=true, language='en') }}) renders=8572>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "relative_time_plus.jinja", line 203, in template
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Undefined is not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Undefined is not in list
```

**Comment by TheFes** [comment]
Could you tell me what kind of entity `config.entity` is? What is the state of this entity when is has a value?

**Comment by Petro31** [comment]
This isn't an issue with this macro.  This is an issue with `config.entity` being undefined.  I assume this is on a frontend card?  If yes, you need to do...
```
{% from 'relative_time_plus.jinja' import relative_time_plus %}
{% if config.entity is defined %}
  {{ 'wait' if not has_value(config.entity) else relative_time_plus(states[config.entity].last_changed, parts=2, week=false, time=true, abbr=true, language='en') }}
{% endif %}

**Comment by erkr** [comment]
Ah thanks for explaining. The config.entity is defined by the  https://github.com/thomasloven/lovelace-template-entity-row.

I expected `has_value()` to gard me for undefined entities. I have some doubts as an undefined entity would already fail on the `state[config.entity]` part.

I will try to use `is defined` instead and see if that solved the issue 👍

**Comment by erkr** [comment]
Update: it got much worse. My log is now spammed with errors and warnings during startup wrt NoneType.
Will add a check on has_value:
``` 
{% if (config.entity is defined) and has_value(config.entity)  %}
```

**Comment by erkr** [comment]
Update2:

Can this be related?!:
![image](https://github.com/TheFes/relative-time-plus/assets/4363599/ace9b0ef-7773-4e9c-801b-ad79ebfaee5e)

**Comment by TheFes** [comment]
Ah, okay. I'll build in a safeguard for that

**Comment by TheFes** [comment]
Should be fixed in v0.3.8 now

**Comment by erkr** [comment]
Will give it a try🥳

**Comment by erkr** [comment]
Looks great, thanks for the fast fix
